list.of.packages <- c("readxl", "magrittr", "ggplot2", "dplyr", "textclean", 
                      "tidyr", "tidytext", "na.tools", "stringr", "smplot2",
                      "gridExtra", "reshape2", "purrr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only=T)
rm(list.of.packages,new.packages)

directory <- "data/"

# Import tibble generated by translation.r.
BindDevtDocs <- read.table(paste0(directory,"BindDevtDocs.csv"), header=TRUE, quote="\"")

# Preprocess text with functions from the textclean package.
TidyBindDocs = BindDevtDocs %>% 
  select(code, id, Country, translation) %>% 
  mutate(tdtext = tolower(replace_non_ascii
                          (replace_curly_quote
                            (replace_html
                              (replace_url
                                (translation)
                              )))))

doc_words <- TidyBindDocs %>%
  unnest_tokens(word, tdtext) %>%
  count(Country, word, sort=TRUE)

total_words <- doc_words %>%
  group_by(Country) %>%
  summarise(total = sum(n))

## ANALYSIS OF SDG GOALS IN NDPs 
# Create a corpus and tokenise with unnest_tokens
TidyBindDocsCountry <- TidyBindDocs %>% group_by(Country) %>%
  summarise(tdtextCountry = toString(tdtext))
devt_tokens <- TidyBindDocsCountry %>%
  unnest_tokens(word, tdtextCountry) %>%
  count(Country, word, sort=TRUE) 
sdg_words <- word_bank %>% select(Goal, word)
devt_sdg <- inner_join(devt_tokens, sdg_words, by = join_by(word), relationship = "many-to-many")

# Compute SDG term frequencies for each country
total_words_country <- devt_tokens %>% 
  group_by(Country) %>% 
  summarise(total = sum(n))
devt_words_country <- left_join(devt_sdg, total_words_country)

FreqCountryWords <- devt_words_country %>%  
  group_by(Country) %>% 
  mutate(rank = row_number(), 
         term_frequency = n/total) %>%  #Normalisation
  ungroup()

# Calculate global frequency of each SDG goal across NDPs
total_global_words <- total_words %>% summarise(grand_total = sum(total))

devt_words_global <- cross_join(devt_sdg %>% 
                                  group_by(Goal) %>% 
                                  summarise(n_sdg = sum(n)), 
                                total_global_words)

FreqGlobalWords <- devt_words_global %>%
  mutate(term_frequency = n_sdg/grand_total)

# VISUALISE global SDG terms across NDPs
SDGPlanGloballyTf <-FreqGlobalWords %>% mutate(GoalShow = paste("Goal",Goal))
cbbPalette <- c("#e5243b", "#DDA63A", "#4C9F38", "#C5192D", "#FF3A21", "#26BDE2", 
                "#FCC30B", "#A21942", "#FD6925", "#DD1367", "#FD9D24", "#BF8B2E", 
                "#3F7E44", "#0A97D9", "#56C02B", "#00689D", "#19486A")

plotSDGGloballyTf <- ggplot(SDGPlanGloballyTf) +
  geom_hline(aes(yintercept = y), data.frame(y = c(0:3) * 10), color = "lightgrey") + 
  geom_col(aes(x = reorder(str_wrap(GoalShow, 5), Goal), y = term_frequency*10000, 
               fill = factor(Goal)),
           position = "dodge2",show.legend = FALSE,alpha = .7) +
  scale_fill_manual(values=cbbPalette) +
  geom_segment(aes(x = reorder(str_wrap(GoalShow, 5), Goal),y = 0,
                   xend = reorder(str_wrap(GoalShow, 5), Goal),yend = 75),
               linetype = "dashed",color = "gray12") + 
  coord_polar()

plotSDGGloballyTf <- plotSDGGloballyTf + 
  ggplot2::annotate(x = 18, y = 25, label = "0.0025", color = "grey12", geom = "text") + 
  ggplot2::annotate(x = 18, y = 50, label = "0.0050", color = "grey12", geom = "text") + 
  ggplot2::annotate(x = 18, y = 75, label = "0.0075", color = "grey12", geom = "text") +
  scale_y_continuous(
    limits = c(-15, 85),
    expand = c(0, 0),
    breaks = c(0, 25, 50, 75)
  ) + 
  theme(
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(color = "gray12", size = 12),
    legend.position = "bottom",
  )

# VISUALISE global SDG plans (highest goal per country)
SDGPlanHighestG <- FreqCountryWords %>%
  group_by(Country, Goal) %>%
  summarise(freqGoal = sum(n), total = mean(total), n = n(), .groups = 'drop') %>%
  mutate(term_frequency = freqGoal/total) %>%
  ungroup() %>%
  group_by(Country) %>%
  filter(term_frequency == max(term_frequency)) %>%
  arrange(desc(term_frequency)) %>%
  mutate(GoalShow = paste("Goal",Goal)) %>%
  ungroup()

SDGPlanHighestSum <- SDGPlanHighestG %>% group_by(Goal, GoalShow) %>% tally() %>% arrange(desc(n))

HighestGraph <- ggplot(SDGPlanHighestSum, aes(x=GoalShow, y=n)) +
  geom_segment( aes(x=reorder(str_wrap(GoalShow, 7), Goal), xend=GoalShow, y=0, yend=n), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) + 
  ylab("Number of Countries") +
  xlab("SDGs")

# Plot the graphs
plotSDGGloballyTf
HighestGraph

## ANALYSIS OF CORRELATION BETWEEN NDPs AND SDG SCORE
SDGPlanAll <- FreqCountryWords %>%
  group_by(Country, Goal) %>%
  summarise(freqGoal = sum(n), total = mean(total), n = n(), .groups = 'drop') %>%
  ungroup() %>%
  mutate(term_frequency = freqGoal/total) %>%
  arrange(desc(term_frequency)) %>%
  mutate(GoalShow = paste("Goal", Goal)) 

# Read dataset from Excel file: SDR 2024 Data
SDR2024Data <- read_excel(paste0(directory,"SDR2024-data.xlsx"), sheet = "Full Database")

# Set SDG labels to use in graph titles
SDGs <- c("1-No Poverty", "2-Zero Hunger", "3-Good Health and Well-Being", 
           "4-Quality Education", "5-Gender Equality", "6-Clean Water and Sanitation", 
           "7-Affordable and Clean Energy", "8-Decent Work and Economic Growth", 
           "9-Industry, Innovation and Infrastructure", "10-Reduced Inequality", 
           "11-Sustainable Cities and Communities", "12-Responsible Consumption and Production", 
           "13-Climate Action", "14-Life Below Water", "15-Life on Land", 
           "16-Peace, Justice and Strong Institutions", "17-Partnerships for the Goals")

# Data preprocessing
goal_scores <- paste0("Goal ", 1:17, " Score")
goalStr <- paste0("goal", 1:17)

# Select relevant columns
LookupForSelect <- c("Country Code ISO3", "Country", "2024 SDG Index Score", 
                     "2024 SDG Index Rank", goal_scores)

# Set mapping for renaming columns
static_rename <- c(
  "Country Code ISO3" = "code", 
  "Country" = "Country", 
  "2024 SDG Index Score" = "sdgScore", 
  "2024 SDG Index Rank" = "sdgRank"
)

dynamic_rename <- setNames(goalStr, goal_scores)
LookupForRename <- c(static_rename, dynamic_rename)

# Select and rename columns
SDRSelectedColumn <- SDR2024Data %>%
  select(all_of(LookupForSelect)) %>%
  rename_with(~ LookupForRename[.x], everything())
write.csv(SDRSelectedColumn, file = paste0(directory,"SDRscore.csv")) 

# SDR Score
SDRCountryAll <- SDRSelectedColumn %>%  
  filter(is.na(sdgScore)=="FALSE") %>%
  mutate(maxGoal = max(goalStr))
SDRCountryAllTr <- SDRCountryAll %>%
  select(Country, all_of(goalStr)) %>% 
  pivot_longer(
    cols = !Country, 
    names_to = "goal", 
    values_to = "score"
  )
SDRCountryAllTr <- SDRCountryAllTr %>%
  mutate(order = str_sub(goal, 5)) %>%
  mutate(goalShow = paste("Goal",str_sub(goal,5)))

# Combine NDPs and SDG Score
SDCountryAll <- inner_join(SDGPlanAll, SDRCountryAllTr, by = c("GoalShow" = "goalShow", "Country" = "Country")) %>%
  select(-total, -goal) %>%
  group_by(Country) %>%
  mutate(sumtm = sum(na.rm(term_frequency))) %>%
  mutate(sumscore = sum(na.rm(score))) %>%
  mutate(tm_pt = term_frequency/sumtm) %>%
  mutate(score_pt = score/sumscore)

# Plot correlation between NDPs and SDG scores in general
# Calculate the confidence interval
res <- cor.test(SDCountryAll$tm_pt, SDCountryAll$score_pt, 
                method = "pearson")
ci.lower <- res$conf.int[1]
ci.upper <- res$conf.int[2]
p_val <- res$p.value
r <- res$estimate

format_p <- function(p) {
  if (p < 0.001) {
    "p < 0.001"
  } else {
    sprintf("p = %.3f", p)
  }
}

# Create combined label
combined_label <- paste0(
  "r = ", sprintf("%.3f", r), ", ",
  format_p(p_val), ", 95% CI [",
  sprintf("%.3f", ci_lower), ", ",
  sprintf("%.3f", ci_upper), "]"
)

ggplot(SDCountryAll, aes(x=tm_pt, y=score_pt)) + 
  geom_point(aes(color = reorder(`GoalShow`, Goal))) +
  scale_color_manual(values = cbbPalette) +
  geom_smooth(method = "lm", se = FALSE) +
  annotate("text", 
           x = max(SDCountryAll$tm_pt, na.rm = TRUE),
           y = max(SDCountryAll$score_pt, na.rm = TRUE),
           label = combined_label, 
           hjust = 1, vjust = 1, size = 4)+
  theme(legend.position = "none")

# Plot correlation berween NDPs and SDGs per Goal, arrange by trend (r)
trend_df <- SDCountryAll %>%
  group_by(Goal) %>%
  summarise(
    r = cor(tm_pt, score_pt, method = "pearson", use = "complete.obs")
  ) %>%
  arrange(desc(r))  
ordered_goals <- trend_df$Goal

plot_list <- list()
for (i in seq_along(ordered_goals)) {
  g <- ordered_goals[i]
  p <- ggplot(
    filter(SDCountryAll, Goal == g),
    aes(x = tm_pt, y = score_pt, color = reorder(GoalShow, Goal))
  ) +
    geom_point() +
    scale_color_manual(values = cbbPalette[g]) +
    labs(
      title = paste(strwrap(SDGs[g], 26), collapse = "\n"),
      x = "", y = ""
    ) +
    sm_statCorr(text_size = 3) +
    theme(
      plot.title = element_text(size = 9),
      axis.text.y = element_text(size = 9),
      axis.text.x = element_text(
        angle = 45, vjust = 0.5, hjust = 0.5, size = 9
      )
    )
  plot_list[[i]] <- p
}
  
grid.arrange(
  grobs=plot_list, 
  ncol=5, nrow=4
) 

# Calculate the False Discovery Rate with the Benjamini-Hochberg Procedure
p_values_tbl <- SDCountryAll %>%
  filter(!is.na(tm_pt), !is.na(score_pt)) %>%
  group_by(Goal) %>%
  summarise(res = list(tidy(cor.test(tm_pt, score_pt, method = "pearson", conf.level = 0.95))),
            .groups = "drop") %>%
  unnest(res) %>%
  transmute(
    Goal,
    r = estimate,
    t = statistic,
    df = parameter,
    p_value = p.value,
    conf.low,
    conf.high
  )

pvalues<-p_values_tbl$p_value
fdrs<-p.adjust(pvalues, method="BH")
p_values_tbl$p_value_adj <- fdrs
write.csv(p_values_tbl, file = paste0(directory,"p_values_tbl.csv")) 

## DATA PREPROCESSING for policy priority / sequential clustering
# Generate TF matrices for SDG goals: MatrixOfTf (NDPs) and MatrixOfScore (SDG performance)
breaks <- c(seq(1,18, by = 1))
labels <- paste("Goal", seq_len(length(breaks) - 1))

MatrixofTf <- SDGPlanAll %>% 
  mutate(bracket = cut(Goal, breaks = breaks, labels = labels, right=FALSE)) %>% 
  group_by(bracket, Country) %>% 
  summarise(term_frequency = sum(term_frequency)) %>% 
  pivot_wider(names_from="bracket", values_from="term_frequency", values_fill = 0)
write.csv(MatrixofTf, file = paste0(directory,"MatrixofTf.csv")) 

MatrixofScore <- SDRCountryAll %>%
  select(-code, -sdgScore, -sdgRank, -maxGoal)
colnames(MatrixofScore) <- c("Country", labels)
write.csv(MatrixofScore, file = paste0(directory,"MatrixofScore.csv")) 

# Create Matrix of Ranks for NDPs (MatrixofRanks) and SDG Performance (MatrixofSDRRanks)
MatrixofRanks <- SDGPlanAll %>%
  select(Country, Goal) %>%
  group_by(Country) %>%
  mutate(rn = row_number()) %>%
  ungroup() %>%
  spread(rn, Goal) 
colnames(MatrixofRanks) <- c("Country", paste0("Rank ", 1:17))
write.csv(MatrixofRanks, file = paste0(directory,"MatrixofRanks.csv")) 

MatrixofSDR <- SDRSelectedColumn[complete.cases(SDRSelectedColumn[ , 5:6]),]
MatrixofSDRRanks <- melt(MatrixofSDR, id.vars=c("code", "Country", "sdgScore", "sdgRank"))
MatrixofSDRRanks <- MatrixofSDRRanks %>% 
  arrange(Country, desc(value)) %>% 
  mutate(Goal = as.numeric(substring(variable, 5))) %>%
  select(Country, Goal) %>%
  group_by(Country) %>%
  mutate(rn = row_number()) %>%
  ungroup() %>%
  spread(rn, Goal) 
colnames(MatrixofSDRRanks) <- c("Country", paste0("Rank ", 1:17))
write.csv(MatrixofSDRRanks, file = paste0(directory,"MatrixofSDRRanks.csv")) 